{% set name = "apache-airflow-providers-ftp" %}
{% set version = "3.13.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_ftp-{{ version }}.tar.gz
  sha256: 2574f041b42a6c6952142392f4540434a6c7ec6ee3760fd5b6b5990e0aac4709

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0

test:
  imports:
    - airflow.providers.ftp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-ftp for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/ftp/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-ftp/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
