{% set name = "apache-airflow-providers-ftp" %}
{% set version = "3.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_ftp-{{ version }}.tar.gz
  sha256: 417bcf35bc8421d1c9bb33f51e81111a8981622f1a9b74be7e5ff8e7c69f1666

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.9.0

test:
  imports:
    - airflow.providers.ftp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-ftp for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/ftp/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-ftp/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
